name: native_contact
description: A Flutter plugin to call native contacts view on Android and iOS devices.
version: 0.0.3
author: Túlio Magalhães <tuliohdvp@gmail.com>
homepage: https://github.com/Tulioh/native_contact

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: flutter.plugins.nativecontact
    pluginClass: NativeContactPlugin